### ISSUE TITLE
Scrape beerdata from bar lists

### ISSUE THREAD

**Issue by heikkilevanto** [heikkilevanto/beertracker#109]
I already have a link for the most common bars beer list. It might not be too hard to scrape beer name, alc, and brewer from that list, if entering a number instead of beer name.

**Comment by heikkilevanto** [comment]
Basically, it boils down to feeling the list page, finding the entry for the right beer, and extracting the values. Those are simple pages, should be easy with a regexp or two.

**Comment by schafdog** [comment]
You do have some experience here...

**Comment by heikkilevanto** [comment]
Sure, but this has always been a low priority.

**Comment by heikkilevanto** [comment]
Thinking how I should approach this.

The process splits nicely into
* Fetch the beer list for the bar
* Parse the values out of it (bar-specific code, regexps, dom stuff, whatever)
* Make a displayable page with buttons to record beer from the list

It all could be integrated into beertracker, but might be better to make a separate script for each bar, doing at least the first two steps. Those scripts should be command-line programs (that can be invoked from beertracker), and output their data in some standardized format, probably one line per beer. Then beertacker could do the formatting and displaying.

**Comment by heikkilevanto** [comment]
Here is an example of how to parse HTML using LibXML, which is a standard tool I know: https://grantm.github.io/perl-libxml-by-example/html.html

**Comment by schafdog** [comment]
Something like this... You can prob. improve it with better perl skills
[oelbaren.pl.txt](https://github.com/heikkilevanto/beertracker/files/6666006/oelbaren.pl.txt)

**Comment by heikkilevanto** [comment]
Ok, Ølbaren works for now. The layout is slightly suboptimal, but good enough for now.

Had to modify the scrip to produce ascii-only JSON (non-ascii characters will be encoded and decoded all right).

Also, dropped the subtype field, parsing the whole thing into type.

Need to fix  the other scripts too.

**Comment by heikkilevanto** [comment]
Ok, Ølsnedkeren and Taphouse work as well. Fermentoren is using Untappd, which is tricky to scrape, see #201.

Could use more scrapers, but they can get their own issues. Closing this.
