### ISSUE TITLE
SqLite

### ISSUE THREAD

**Issue by heikkilevanto** [heikkilevanto/beertracker#349]
Reading the file is fast enough, but parsing every line does take some time. I have tried to reduce that, but it is getting clumsy. At some point I will have to start using some more advanced data back end. SqLite seems like the next obvious level. This issue is for collecting ideas and comments about that change before jumping in, for it will be an almost complete rewrite of the system.

Tables
* Drinks - Beers, Wines, etc. Anything with volume and alc
  *  Add a new field for std drinks (=alc*vol/onedrink), so we can sum them directly in SQL
* Locations - Keep them separate, so we can track geo coords etc.
* Comments - Restaurants, nights, people and such
* Do NOT make tables for beers, breweries, or styles(?), they can change over time. Too clumsy to have to enter those separately, especially for new users.

How to get there
* Convert the data
* Read the whole data from SqLite instead of the table, as now
* Redo each page to fetch its own data

**Comment by heikkilevanto** [comment]
Might make sense to have one table for "drinks" that handles type, volume, price, alc. And separate tables for wine/beer/booze details. That would make statistics faster to collect since we can ignore the details.

**Comment by heikkilevanto** [comment]
Instead of the incremental way mentioned in the initial comment, I am thinking of a complete rewrite. It would allow for more possibilities and benefits:

- More complex data model
- Cleaning up old cruft that has collected in small corners
- Change programming language in the  back end (Go? Python?) and use more advanced libraries and frameworks (html, graphs, etc)

Of course a rewrite has its drawbacks:

- Takes time and work
- Need to keep the old system alive, but develop in the new one
- Migrate data into the new system while developing, and once for the official switch-over
- Risks new and improved bugs
- Risk of not getting it ever ready enough to move over

**Comment by schafdog** [comment]
That's a big conclusion. Prob. need to a beer or two before final decision ;-D

**Comment by heikkilevanto** [comment]
One possible first step would be to design the SQL table layout, make a conversion script (by cannibalizing a copy of the current program) and playing with that, checking what queries various pages would need, and how they would perform.

At the same time it ought to be possible to make simple test programs for producing the HTML pages, in what ever language I may wish to play with.  Just the input form, and maybe a list of the most recent beers.

But as noted before, this needs some beer and discussion!

**Comment by heikkilevanto** [comment]
Did make some experiments with Chatgtp, it produced an almost reasonable python script to convert the existing data into a SqLite database in about an hour of messing around with it. 

Made also an experiment just to parse the file. Surprisingly fast, 200ms for reading and parsing the whole file. Something else must be taking the time in my current script.

**Comment by heikkilevanto** [comment]
Have defined the database and can import data into it. All these have their own issues, closing this one
